name: Generate Snake

on:
  schedule:
    # Execute uma vez por dia
    - cron: "0 0 * * *"

  workflow_dispatch:
  push:
    branches:
      - main  # ou a branch principal do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: gvpsilva
          outputs: dist
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
